// GENERATED by scripts/brain-gen-taxonomy.mjs from docs/riskware_rubrics_processed.xlsx.
// Do not hand-edit. Regenerate with: node scripts/brain-gen-taxonomy.mjs
import type { Strength } from "@/brain/types";

export interface TaxonomySignal { id: string; name: string; strength: Strength }
export interface TaxonomyRubric { id: string; name: string; description: string; signals: TaxonomySignal[] }

export const RISKWARE_TAXONOMY: TaxonomyRubric[] = [
  {
    "id": "attribution_gated_webview_uncloaking",
    "name": "MMP cloaking",
    "description": "App contains custom implementations of user conversion flows",
    "signals": [
      {
        "id": "attribution_gated_webview_uncloaking__app_stores_conversion_data",
        "name": "App stores conversion data",
        "strength": "medium"
      },
      {
        "id": "attribution_gated_webview_uncloaking__app_loads_affiliate_link_into_a_webview_w_conversion_data",
        "name": "App loads affiliate link into a Webview w/ conversion data",
        "strength": "strong"
      },
      {
        "id": "attribution_gated_webview_uncloaking__app_sends_conversion_data_to_a_remote_endpoint_not_to_ads_provid",
        "name": "App sends conversion data to a remote endpoint (not to Ads provider)",
        "strength": "weak"
      },
      {
        "id": "attribution_gated_webview_uncloaking__conversion_flow_is_empty",
        "name": "Conversion flow is empty",
        "strength": "non_signal"
      },
      {
        "id": "attribution_gated_webview_uncloaking__app_changes_its_behavior_based_on_conversion_data_e_g_organic_no",
        "name": "App changes its behavior based on conversion data (e.g. Organic/NonOrganic)",
        "strength": "strong"
      }
    ]
  },
  {
    "id": "install_referrer_cloaking",
    "name": "Install Referrer cloaking",
    "description": "App behaves differently based on the parameters collected from the install referrer",
    "signals": [
      {
        "id": "install_referrer_cloaking__google_play_install_referrer",
        "name": "Google Play Install Referrer",
        "strength": "medium"
      }
    ]
  },
  {
    "id": "runtime_loading_of_code",
    "name": "Runtime loading of code",
    "description": "Dynamically downloading and executing code after the app is installed with the capability to introduce updates without user knowledge.",
    "signals": [
      {
        "id": "runtime_loading_of_code__dynamically_loading_dex_elf_files_from_server_side",
        "name": "Dynamically loading dex/elf files from server side",
        "strength": "strong"
      },
      {
        "id": "runtime_loading_of_code__run_classloaders_from_elf_files",
        "name": "Run Classloaders from elf files",
        "strength": "medium"
      },
      {
        "id": "runtime_loading_of_code__cocos_update_hotupdate_reload_external_javascript_files",
        "name": "Cocos update (hotupdate). Reload external Javascript files",
        "strength": "weak"
      },
      {
        "id": "runtime_loading_of_code__unity_update_downloads_bundle_files_from_server_side_to_update_f",
        "name": "Unity update, Downloads bundle files from server side to update functionality",
        "strength": "weak"
      },
      {
        "id": "runtime_loading_of_code__decryption_and_execution_of_an_existing_file_in_assets",
        "name": "Decryption and execution of an existing file in assets",
        "strength": "medium"
      }
    ]
  },
  {
    "id": "geolocation_cloaking",
    "name": "Geolocation cloaking",
    "description": "Altering behavior based on perceived location",
    "signals": [
      {
        "id": "geolocation_cloaking__sim_operator",
        "name": "SIM Operator",
        "strength": "weak"
      },
      {
        "id": "geolocation_cloaking__device_language",
        "name": "Device language",
        "strength": "weak"
      },
      {
        "id": "geolocation_cloaking__timezone",
        "name": "Timezone",
        "strength": "weak"
      },
      {
        "id": "geolocation_cloaking__mcc_code",
        "name": "MCC code",
        "strength": "weak"
      },
      {
        "id": "geolocation_cloaking__android_billable_currency",
        "name": "Android billable currency",
        "strength": "weak"
      },
      {
        "id": "geolocation_cloaking__app_checks_if_it_s_operating_under_specifically_google_infrastru",
        "name": "App checks if it's operating under specifically google infrastructure (generally via IP check)",
        "strength": "strong"
      }
    ]
  },
  {
    "id": "arbitrary_obfuscated_url_loading",
    "name": "Arbitrary or obfuscated URL loading",
    "description": "Loading unpredictable or misleading URLs to disguise intent that might trigger behavior change",
    "signals": [
      {
        "id": "arbitrary_obfuscated_url_loading__obfuscated_url",
        "name": "Obfuscated URL",
        "strength": "weak"
      },
      {
        "id": "arbitrary_obfuscated_url_loading__persisting_and_reloading_a_redirected_url",
        "name": "Persisting and Reloading a Redirected URL",
        "strength": "strong"
      },
      {
        "id": "arbitrary_obfuscated_url_loading__loads_url_from_http_tcp_udp_response_in_webview_not_from_ads_pro",
        "name": "Loads URL from HTTP/TCP/UDP Response in webview (NOT from ads provider)",
        "strength": "strong"
      },
      {
        "id": "arbitrary_obfuscated_url_loading__loads_url_from_http_tcp_udp_response_in_external_browser_via_int",
        "name": "Loads URL from HTTP/TCP/UDP Response in external browser via intent (NOT from ads provider)",
        "strength": "strong"
      },
      {
        "id": "arbitrary_obfuscated_url_loading__loadurl_of_a_website_obtained_from_firebase",
        "name": "LoadUrl of a website obtained from firebase",
        "strength": "strong"
      },
      {
        "id": "arbitrary_obfuscated_url_loading__app_retrieves_a_url_that_would_break_policy_if_loaded_from_a_1st",
        "name": "App retrieves a URL that would break policy if loaded from a 1st party C2",
        "strength": "medium"
      },
      {
        "id": "arbitrary_obfuscated_url_loading__url_from_external_configuration_sdk",
        "name": "URL from External Configuration (SDK)",
        "strength": "strong"
      },
      {
        "id": "arbitrary_obfuscated_url_loading__static_app_loads_url_conditionally_according_to_another_static_e",
        "name": "[Static] App loads URL conditionally according to another static evasion signal",
        "strength": "strong"
      },
      {
        "id": "arbitrary_obfuscated_url_loading__app_loads_privacy_policy_with_deep_link_in_html",
        "name": "App loads privacy policy with deep link in HTML",
        "strength": "medium"
      },
      {
        "id": "arbitrary_obfuscated_url_loading__app_loads_bare_non_private_ip_into_webview",
        "name": "App loads bare non-private IP into WebView",
        "strength": "medium"
      }
    ]
  },
  {
    "id": "network_information_cloaking",
    "name": "Network information cloaking",
    "description": "Alters behaviour based on network information",
    "signals": [
      {
        "id": "network_information_cloaking__vpn_connection_available_check",
        "name": "VPN connection available check",
        "strength": "weak"
      },
      {
        "id": "network_information_cloaking__ip_location_check",
        "name": "IP location check",
        "strength": "weak"
      },
      {
        "id": "network_information_cloaking__proxy_check",
        "name": "Proxy check",
        "strength": "weak"
      },
      {
        "id": "network_information_cloaking__ip_api",
        "name": "IP API",
        "strength": "weak"
      },
      {
        "id": "network_information_cloaking__mobile_data_connection",
        "name": "Mobile data connection",
        "strength": "weak"
      }
    ]
  },
  {
    "id": "device_info_cloaking",
    "name": "Device info cloaking",
    "description": "Changes behaviour based on device information",
    "signals": [
      {
        "id": "device_info_cloaking__battery_percentage",
        "name": "Battery percentage",
        "strength": "medium"
      },
      {
        "id": "device_info_cloaking__root_detection",
        "name": "Root Detection",
        "strength": "weak"
      },
      {
        "id": "device_info_cloaking__emulator_detection",
        "name": "Emulator Detection",
        "strength": "weak"
      },
      {
        "id": "device_info_cloaking__touch_count",
        "name": "Touch count",
        "strength": "weak"
      },
      {
        "id": "device_info_cloaking__motion_detection",
        "name": "Motion detection",
        "strength": "medium"
      },
      {
        "id": "device_info_cloaking__development_settings_enabled_check",
        "name": "development_settings_enabled check",
        "strength": "weak"
      },
      {
        "id": "device_info_cloaking__requiring_packages_to_be_installed_or_not_installed",
        "name": "Requiring packages to be installed or not installed",
        "strength": "medium"
      },
      {
        "id": "device_info_cloaking__android_hardware_info_fingerprint_model_manufacturer_ro_build_id",
        "name": "Android hardware info (fingerprint, model, manufacturer, ro.build.id, etc.)",
        "strength": "medium"
      },
      {
        "id": "device_info_cloaking__adb_enabled_detection",
        "name": "adb_enabled detection",
        "strength": "weak"
      }
    ]
  },
  {
    "id": "time_cloaking",
    "name": "Time cloaking",
    "description": "Triggers different behaviour based on device time",
    "signals": [
      {
        "id": "time_cloaking__time_based_behavior_change",
        "name": "Time Based Behavior Change",
        "strength": "strong"
      }
    ]
  },
  {
    "id": "command_and_control",
    "name": "Command And Control",
    "description": "Infrastructure used by Riskware Developers",
    "signals": [
      {
        "id": "command_and_control__known_riskware_urls_a_url_is_considered_known_riskware_url_if_it",
        "name": "Known riskware URLs. \r\nA URL is considered known Riskware URL if it has been used by at least\r\n5 Apps on Play and 2 of them (0.4 Precision) have been found as TP for Riskware Major. \r\n\r\nNote: Precision should be >= 0.4\r\nNote: You might use either the full domain or \r\nthe root one as long as DONT's are followed. (e.g., www.example.com or example.com)",
        "strength": "strong"
      }
    ]
  },
  {
    "id": "partial_uncloaking",
    "name": "Partial uncloaking",
    "description": "Behavior change is confirmed without evidence of the final payload",
    "signals": [
      {
        "id": "partial_uncloaking__non_operational_behavior_change",
        "name": "Non-operational Behavior Change",
        "strength": "strong"
      }
    ]
  }
];

export const TAXONOMY_RUBRIC_COUNT = 10;
export const TAXONOMY_SIGNAL_COUNT = 44;
